### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by enelesmai**
* Added header with position fixed when scrolling
* added navigator
* added featured section
* added sponsored insights
* Added editor's pick section
* added slideshows section
* added magazine section
* Added subscriber section
* added footer
* used bootstrap

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @enelesmai  :wave: 

### Your project looks professional and your page looks very similar to the original this is a great effort :muscle: but I've noticed you are missing the changes in some breakpoints, so please make the following changes :point_down: 

## Small screens

**Section Positioning**

- [x] please follow the structure for the first 4 sections in this screen size:

1. TOP STORY
2. MORE STORIES
3. CULTURE & TRAVEL
4. FEATURED STORIES

- Yours 

image

- Original

image

**MORE STORIES, LATEST NEWS, and the aside articles for the U.S, World, Business, Tech & Science, Culture and Sports**

- [x] The image of the aside articles of these sections should take 60% of the screen width and the content only 40%

- Yours

image

- Original

image

**Footer**

- [x] The copyright and social icons should be in separate rows taking 100% of the screen width bellow the NEWSWEEK logo

- Yours

image

- Original

image

## Small  and Medium screens

**Navbar**

- [x] please change it so it looks like the original when the screen has less than 992 px width

- Yours

image

- Original

image

## Big screens

- [x] The links search bar should be smaller and the links should take more space also the font should be bigger in size

- Yours

image

- Original

image

## Bootstrap Usage

- [ ] this project is all about using bootstrap so please use it everywhere you can delete all of these selectors in your CSS file and use bootstrap classes directly in your HTML file

- padding: (all padding selectors)
- margin: (all margin selectors)
- color: (white, red, black)
- background-color: (white, red, black)
- display: (none, inline, inline-block, flex, etc)
- justify-content: (center, left, right, etc.)
- text-align: (center, left, right, etc.)
- text-transform: (capitalize, uppercase, etc)
- border: unset; (all border selectors)
- font-weight (light, bold, bolder, etc.)

## That's it! :raised_hands: 

## Please :pray: do the changes :memo:  and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

Any questions? ask me on slack! **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @enelesmai great job implementing the changes requested by the previous reviewer. 👍 However, In the ```Latest news``` section on ```Small screen``` the text overlaps into the image. As seen below
yes
- Kindly implement the change requested by the previous reviewer under the ```Bootstrap Section```
cha

Kindly make these changes and submit code review 🙂 
Good luck with your next submission 👍 
Daniel Larbi Addo

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @enelesmai :handshake: 

### Thank you for doing my changes and the changes requested by the previous reviewer :medal_sports: 

### I have no more styling changes for you :no_good_woman:  but with the changes you made some sections were hidden let's show them! :point_down: 

## Medium screens

- [x] the OPINION and LATEST NEWS sections are hidden let's show them

- Yours

image

- Original

image

### That's it! :raised_hands: 

### Please :pray: make the change :memo:  and submit back for a code review when you are done :rocket: 

Happy coding! :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by enelesmai** [comment]
Changes made for medium size

**Comment by lekegitrepo** [comment]
**Hi @enelesmai, well done** 👏 
The OPINION and LATEST NEWS sections are **_fixed in small screen_** but still **_remain hidden in the medium screen_** 

image

**For the small screen it appears:
This is it on the small screen**
image

**But it doesn't appear in the medium screen as mentioned above.**
**_Kindly fix this and resubmit for another review_**. So that it can be approved because you have put a lot of effort into it.

If you have any doubt or questions contact me on slack.

**Reviewed by:** **_Temitayo Adeleke_**
-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
**_Status: Requires Changes_**

**Comment by enelesmai** [comment]
changes made on sm screen and also fixed an overlap issue on more-stories section

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hi @enelesmai :wave: 

### Thank you for doing the changes please :pray:  fix the HTML errors found by the [validator](https://validator.w3.org/#validate_by_upload) and submit back for a code review 

image

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by majovanilla** [comment]
Hi @enelesmai !

## Good job implementing the requested changes on this project! 👍

You are good to go!! This project has been **APPROVED**!

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Some of your images don't have the right width and lose proportion when resizing the screen. You can fix them to make them look right. See screenshot below:

Screenshot from 2020-02-20 22-42-02
Screenshot from 2020-02-20 22-49-01

**STATUS: Project approved.**

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by enelesmai** [comment]
Made changes, thank you for your feedback everyone!

**Pull request merged**
